# FROM ubuntu:22.04 AS final
FROM nvidia/cuda:12.3.2-runtime-ubuntu22.04 AS final

# Set non-interactive mode to avoid prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

# Define the model storage path
ENV OLLAMA_MODELS=/models
ENV MODEL_NAME="deepseek-r1:1.5b"

# Install required dependencies
RUN apt update && apt install -y \
    curl \
    git \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Install Ollama
RUN curl -fsSL https://ollama.com/install.sh | sh

# Set WORKDIR for clarity
WORKDIR $OLLAMA_MODELS

COPY ./run-ollama.sh /tmp/run-ollama.sh

WORKDIR /tmp

RUN chmod +x run-ollama.sh \
    && ./run-ollama.sh

# Expose Ollama's default port (if needed)
EXPOSE 11434

ENTRYPOINT ["/bin/ollama"]
CMD ["serve"]
