apiVersion: v1
kind: Namespace
metadata:
  name: crewai
  labels:
    name: crewai
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: kubernetes-dashboard
#   labels:
#     name: kubernetes-dashboard
---
apiVersion: v1
kind: Namespace
metadata:
  name: ollama
  labels:
    name: ollama
