apiVersion: v1
kind: Service
metadata:
  name: openweb-ui-svc
  namespace: openwebui
spec:
  selector:
    app: openweb-ui
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 8080
  type: LoadBalancer