apiVersion: apps/v1
kind: Deployment
metadata:
  name: openweb-ui
  namespace: openwebui
  labels:
    app: openweb-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openweb-ui
  template:
    metadata:
      labels:
        app: openweb-ui
    spec:
## deployment waits for pvc & /app/backend/data directory setup to be finished
      initContainers:
      - name: check-pvc
        image: busybox
        command: ["sh", "-c", "mkdir -p /app/backend/data && echo 'PVC is ready'"]
        volumeMounts:
        - mountPath: "/app/backend/data"
          name: openweb-data
      containers:
      - name: openweb-ui
        image: ghcr.io/open-webui/open-webui:main
        envFrom:
        - configMapRef:
            name: openwebui-cm
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: openweb-data
          mountPath: /app/backend/data
      volumes:
      - name: openweb-data
        persistentVolumeClaim:
          claimName: openweb-ui-pvc