apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openweb-ui-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard