apiVersion: v1
kind: Service
metadata:
  name: crewai-ui-external
  namespace: crewai-ui
spec:
  type: LoadBalancer
  selector:
    app: crewai-ui
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 8501
