apiVersion: v1
kind: Service
metadata:
  name: ollama-service-tiny
  namespace: ollama
spec:
  type: ClusterIP
  selector:
    app: ollama
    model: tiny
  ports:
    - protocol: TCP
      port: 11434 
      targetPort: 11434

---
apiVersion: v1
kind: Service
metadata:
  name: ollama-service-large
  namespace: ollama
spec:
  type: ClusterIP
  selector:
    app: ollama
    model: large
  ports:
    - protocol: TCP
      port: 11434 
      targetPort: 11434
