apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ollama
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: openweb-ui-svc
  namespace: ollama
spec:
  selector:
    app: openweb-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer