apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-cm
  namespace: n8n
data:
  N8N_RUNNERS_ENABLED: "true"
  N8N_DIAGNOSTICS_ENABLED: "false"
  N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
  N8N_TEMPLATES_ENABLED: "false"
  # N8N_USER_FOLDER: "/home/n8n-storage"
  # N8N_CONFIG_FILES: "/home/n8n-storage/config"
  OLLAMA_BASE_URLS: "http://ollama-service-tiny.ollama.svc.cluster.local:11434;http://ollama-service-large.ollama.svc.cluster.local:11434"
