apiVersion: v1
kind: Service
metadata:
  name: n8n-external
  namespace: n8n
spec:
  type: LoadBalancer
  selector:
    app: n8n
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 5678
