apiVersion: apps/v1
kind: Deployment
metadata:
  name: crewai-deployment
  namespace: crewai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crewai
  template:
    metadata:
      labels:
        app: crewai
    spec:
      containers:
        - name: crewai-container
          image: ghcr.io/organicsoylent/crewai:latest
          imagePullPolicy: IfNotPresent
          env:
            name: OLLAMA_SVC ## change
            value: "http://ollama-service-large.ollama.svc.cluster.local:11434"
            name: SERPER_API_KEY
            valueFrom:
              secretKeyRef:
                name: serper-api-key
                key: SERPER_API_KEY
          ports:
            - containerPort: 80
