apiVersion: apps/v1
kind: Deployment
metadata:
  name: crewai-deployment
  namespace: crewai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crewai
  template:
    metadata:
      labels:
        app: crewai
    spec:
      containers:
        - name: crewai-container
          image: ghcr.io/organicsoylent/crewai:latest
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: crewai-cm
          - secretRef:
              name: crewai-secrets
          ports:
            - containerPort: 80
