# apiVersion: v1
# kind: Service
# metadata:
#   name: talkto-ollama-service
#   namespace: crewai
# spec:
#   selector:
#     app: ollama
#   ports:
#     - protocol: TCP
#       port: 11434
#       targetPort: 11434
# ---
apiVersion: v1
kind: Service
metadata:
  name: crewai-external
  namespace: crewai
spec:
  type: LoadBalancer
  selector:
    app: crewai
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9001
