apiVersion: v1
kind: Service
metadata:
  name: crewai-external
  namespace: crewai
spec:
  type: LoadBalancer
  selector:
    app: crewai
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 8080
