name: Build and Push Docker Images

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
permissions:
  contents: read
  packages: write
  
env:
  MODEL_NAME: "deepseek-r1:1.5b"

jobs:
#### Ollama Section ####
download-model:
  runs-on: ubuntu-latest
  steps:
    - name: Install Ollama
      run: curl -fsSL https://ollama.com/install.sh | sh 

    - name: Start Ollama and Pull Model
      run: |
        echo "Starting Ollama server in the background..."
        ollama serve &

        echo "Waiting for Ollama server to be active..."
        while ! ollama list >/dev/null 2>&1; do
          sleep 1
        done

        echo "Ollama server is running. Pulling model..."
        ollama pull $MODEL_NAME

    - name: Upload model as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ollama-model
        path: /root/.ollama/models/

  build-image-ollama:
    needs: download-model
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Download the model artifact
      uses: actions/download-artifact@v4
      with:
        name: ollama-model
        path: ollama-models/
    - name: Log in to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Ollama image
      run: |
        docker build \
          --build-arg MODEL_NAME=$MODEL_NAME \
          -t ghcr.io/organicsoylent/ollama:latest \
          --file ollama-deployment/Dockerfile \
          --build-context models=/root/.ollama/models/ \
          ollama-deployment/
    - name: Save image for testing
      run: docker save ghcr.io/organicsoylent/ollama:latest -o ollama.tar
    - name: Upload image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ollama
        path: ollama.tar

  test-ollama:
    needs: build-image-ollama
    runs-on: ubuntu-latest
    steps:
      - name: Download ollama image
        uses: actions/download-artifact@v4
        with:
          name: ollama
      - name: Load Docker images
        run: |
          docker load -i ollama.tar
      - name: Run ollama and test
        run: |
          docker run --rm --name ollama-test ghcr.io/organicsoylent/ollama:latest bash -c "
              ollama serve & 
              while ! ollama list >/dev/null 2>&1; do 
                  echo 'Waiting for Ollama to start...'; 
                  sleep 1; 
              done; 
              ollama list | grep 'deepseek-r1:1.5b' || exit 1
          "

  push-ollama:
    needs: test-ollama
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download Ollama image
        uses: actions/download-artifact@v4
        with:
          name: ollama
      - name: Load and Push Ollama image
        run: |
          docker load -i ollama.tar
          docker push ghcr.io/organicsoylent/ollama:latest

#### CrewAI Section ####
  build-image-crewai:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Log in to ghcr
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & Push CrewAI image
      run: |
        docker build -t ghcr.io/organicsoylent/crewai:latest crewai-deployment/
    - name: Save image for testing
      run: docker save ghcr.io/organicsoylent/crewai:latest -o crewai.tar
    - name: Upload image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: crewai
        path: crewai.tar

  test-crewai:
    needs: build-image-crewai
    runs-on: ubuntu-latest
    steps:
      - name: Download crewai image
        uses: actions/download-artifact@v4
        with:
          name: crewai
      - name: Load Docker images
        run: |
          docker load -i crewai.tar
      - name: Run crewai and test
        run: |
          docker run --rm ghcr.io/organicsoylent/crewai:latest python -c "import sys; print('Python is working:', sys.version)"

  push-crewai:
    needs: test-crewai
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download CrewAI image
        uses: actions/download-artifact@v4
        with:
          name: crewai
      - name: Load and Push CrewAI image
        run: |
          docker load -i crewai.tar
          docker push ghcr.io/organicsoylent/crewai:latest

